services:
    haproxy:
        build:
            context: ./haproxy
            dockerfile: Dockerfile
        container_name: haproxy
        hostname: haproxy
        depends_on:
            - rabbitmq1
            - rabbitmq2
            - rabbitmq3
        ports:
            - "1936:1936"
            - "5672:5672"
            - "15672:15672"
        environment:
            FRONTEND_PORT : 5672
            BACKENDS: "rabbitmq1:5672 rabbitmq2:5672 rabbitmq3:5672"
            DNS_ENABLED: "true"
            LOG_LEVEL: "info"

    rabbitmq1:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        container_name: rabbitmq1
        hostname: rabbitmq1
        environment:
            RABBITMQ_ERLANG_COOKIE: cookie
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15673:15672

    rabbitmq2:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        container_name: rabbitmq2
        hostname: rabbitmq2
        environment:
            RABBITMQ_ERLANG_COOKIE: cookie
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15674:15672

    rabbitmq3:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        container_name: rabbitmq3
        hostname: rabbitmq3
        environment:
            RABBITMQ_ERLANG_COOKIE: cookie
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15675:15672