version: '3.7'

services:
    haproxy:
        image: "haproxy_test"
        hostname: haproxy
        depends_on:
            - rabbitmq1
            - rabbitmq2
            - rabbitmq3
        ports:
            - "1936:1936"
            - "5672:5672"
            - "15672:15672"
        environment:
            FRONTEND_PORT : 5672
            BACKENDS: "rabbitmq1:5672 rabbitmq2:5672 rabbitmq3:5672"
            DNS_ENABLED: "true"
            LOG_LEVEL: "info"

    rabbitmq1:
        image: "rabbitmq_test"
        hostname: rabbitmq1
        deploy:
            restart_policy:
                delay: 0s
        environment:
            RABBITMQ_ERLANG_COOKIE: cookie
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15673:15672
        volumes:
          - rabbitmq_mnesia:/var/lib/rabbitmq

    rabbitmq2:
        image: "rabbitmq_test"
        hostname: rabbitmq2
        deploy:
            restart_policy:
                delay: 0s
        environment:
            RABBITMQ_ERLANG_COOKIE: cookie
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15674:15672
        volumes:
          - rabbitmq_mnesia2:/var/lib/rabbitmq

    rabbitmq3:
        image: "rabbitmq_test"
        hostname: rabbitmq3
        deploy:
            restart_policy:
                delay: 0s
        environment:
            RABBITMQ_ERLANG_COOKIE: cookie
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15675:15672
        volumes:
          - rabbitmq_mnesia3:/var/lib/rabbitmq

volumes:
  rabbitmq_mnesia:
  rabbitmq_mnesia2:
  rabbitmq_mnesia3: